---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Show current environment
      shell: |
        pwd
        whoami
        ps -ef
      register: result

    - debug:
        var: result.stdout_lines
