---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Show hostname
      command: hostname
      register: host

    - debug:
        var: host.stdout

    - name: Show yes processes
      shell: ps -ef | grep yes
      register: psout
      ignore_errors: true

    - debug:
        var: psout.stdout_lines
